CREATE PROCEDURE GetEmpOneFirstNameFromOut (out OUT_PARAM VARCHAR(255)) language java external name 'ee.jakarta.tck.persistence.storedprocedures.CS_Procs.GetEmpOneFirstNameFromOut' parameter style java;

CREATE PROCEDURE GetEmpFirstNameFromOut (in IN_PARAM INTEGER, out OUT_PARAM VARCHAR(255)) language java external name 'ee.jakarta.tck.persistence.storedprocedures.CS_Procs.GetEmpFirstNameFromOut' parameter style java;

CREATE PROCEDURE GetEmpLastNameFromInOut (inout INOUT_PARAM VARCHAR(255)) language java external name 'ee.jakarta.tck.persistence.storedprocedures.CS_Procs.GetEmpLastNameFromInOut' parameter style java;

CREATE PROCEDURE GetEmpASCFromRS() language java dynamic result sets 1 external name 'ee.jakarta.tck.persistence.storedprocedures.CS_Procs.GetEmpASCFromRS' parameter style java;

CREATE PROCEDURE GetEmpIdFNameLNameFromRS (in IN_PARAM INTEGER) language java dynamic result sets 1 external name 'ee.jakarta.tck.persistence.storedprocedures.CS_Procs.GetEmpIdFNameLNameFromRS' parameter style java;

CREATE PROCEDURE GetEmpIdUsingHireDateFromOut (in IN_PARAM DATE, out OUT_PARAM INTEGER) language java external name 'ee.jakarta.tck.persistence.storedprocedures.CS_Procs.GetEmpIdUsingHireDateFromOut' parameter style java;

CREATE PROCEDURE UpdateEmpSalaryColumn() language java external name 'ee.jakarta.tck.persistence.storedprocedures.CS_Procs.UpdateEmpSalaryColumn' parameter style java;

CREATE PROCEDURE DeleteAllEmp() language java external name 'ee.jakarta.tck.persistence.storedprocedures.CS_Procs.DeleteAllEmp' parameter style java;

CREATE FUNCTION REPLACE (origin_string VARCHAR(255), old_string VARCHAR(255), new_string VARCHAR(255)) RETURNS VARCHAR(255) language java external name 'ee.jakarta.tck.persistence.storedprocedures.CS_Procs.ReplaceString' parameter style java;





CREATE TABLE PHONE_TABLE ( ID VARCHAR(255)   PRIMARY KEY NOT NULL, AREA VARCHAR(255) , PHONE_NUMBER VARCHAR(255) , FK_FOR_ADDRESS VARCHAR(255) );

CREATE TABLE ADDRESS ( ID VARCHAR(255)   PRIMARY KEY NOT NULL, STREET VARCHAR(255) , CITY VARCHAR(255) , STATE VARCHAR(255) , ZIP VARCHAR(255) );

CREATE TABLE CUSTOMER_TABLE ( ID VARCHAR(255)   PRIMARY KEY NOT NULL, NAME VARCHAR(255), COUNTRY VARCHAR(255), CODE VARCHAR(255), FK5_FOR_CUSTOMER_TABLE VARCHAR(255) , FK6_FOR_CUSTOMER_TABLE VARCHAR(255));


CREATE TABLE CUST_TABLE ( CUST_ID VARCHAR(255) PRIMARY KEY NOT NULL, NAME VARCHAR(255), COUNTRY VARCHAR(255), CODE VARCHAR(255));

CREATE TABLE PHONES (ID VARCHAR(255), phones_ORDER INT , PHONE_NUMBER VARCHAR(255), FK_FOR_PHONES VARCHAR(255));
ALTER TABLE PHONES ADD CONSTRAINT FK_FOR_PHONES FOREIGN KEY (FK_FOR_PHONES) REFERENCES CUST_TABLE (CUST_ID) ;

CREATE TABLE EMPLOYEES (ID VARCHAR(255), LASTNAMEEMPLOYEES VARCHAR(255), FK_FOR_EMPLOYEES VARCHAR(255));
ALTER TABLE EMPLOYEES ADD CONSTRAINT FK_FOR_EMPLOYEES FOREIGN KEY (FK_FOR_EMPLOYEES) REFERENCES CUST_TABLE (CUST_ID) ;

CREATE TABLE TRIM_TABLE ( ID VARCHAR(255)   PRIMARY KEY NOT NULL, NAME CHAR(30) NOT NULL);

CREATE TABLE ALIAS_TABLE ( ID VARCHAR(255)   PRIMARY KEY NOT NULL, ALIAS VARCHAR(255) , FK1_FOR_CUSTOMER_TABLE VARCHAR(255) , FK2_FOR_CUSTOMER_TABLE VARCHAR(255) );

CREATE TABLE FKS_ALIAS_CUSTOMER ( FK_FOR_CUSTOMER_TABLE VARCHAR(255)  NOT NULL, FK_FOR_ALIAS_TABLE VARCHAR(255) );

CREATE TABLE FKS_ANOOP_CNOOP( FK8_FOR_CUSTOMER_TABLE VARCHAR(255) , FK2_FOR_ALIAS_TABLE VARCHAR(255));

CREATE TABLE CREDITCARD_TABLE ( ID VARCHAR(255)   PRIMARY KEY NOT NULL, TYPE VARCHAR(255) , EXPIRES VARCHAR(255) , APPROVED BOOLEAN , CREDITCARD_NUMBER VARCHAR(255) , BALANCE DOUBLE, FK3_FOR_CUSTOMER_TABLE VARCHAR(255) , FK_FOR_ORDER_TABLE VARCHAR(255) );

CREATE TABLE ORDER_TABLE ( ID VARCHAR(255)   PRIMARY KEY NOT NULL, ORDERS3_ORDER INT, TOTALPRICE DOUBLE , FK4_FOR_CUSTOMER_TABLE VARCHAR(255) , FK0_FOR_LINEITEM_TABLE VARCHAR(255) );

CREATE TABLE PRODUCT_DETAILS ( ID VARCHAR(255)  PRIMARY KEY NOT NULL, WHOUSE VARCHAR(255) , LICENSE_KEY INT);

CREATE TABLE PRODUCT_TABLE ( ID VARCHAR(255) PRIMARY KEY NOT NULL, NAME VARCHAR(255) , PRICE DOUBLE, QUANTITY INT, PNUM INT, PRODUCT_TYPE VARCHAR(255), INCEPTION DATE, SOLD DATE, MODEL INT, REV DOUBLE);

CREATE TABLE PRODUCT_TABLE_DISCRIMINATOR ( ID VARCHAR(255) PRIMARY KEY NOT NULL, NAME VARCHAR(255), QUANTITY INT, PNUM INT, PRICE DOUBLE, PRODUCT_TYPE INT);

CREATE TABLE PRICED_PRODUCT_TABLE (ID VARCHAR(255) PRIMARY KEY NOT NULL, NAME VARCHAR(255), PRICE DOUBLE, QUANTITY INT, PNUM INT) ;

CREATE TABLE INFO_TABLE (ID VARCHAR(255) PRIMARY KEY NOT NULL, INFOSTREET VARCHAR(255), INFOCITY VARCHAR(255), INFOSTATE VARCHAR(255), INFOZIP VARCHAR(255), FK_FOR_SPOUSE_TABLE VARCHAR(255) ) ;

CREATE TABLE SPOUSE_TABLE (ID VARCHAR(255) PRIMARY KEY NOT NULL,  FIRSTNAME VARCHAR(255), MAIDENNAME VARCHAR(255), LASTNAME VARCHAR(255), SOCSECNUM VARCHAR(255), FK7_FOR_CUSTOMER_TABLE VARCHAR(255), FK_FOR_INFO_TABLE VARCHAR(255) );

CREATE TABLE LINEITEM_TABLE ( ID VARCHAR(255)   PRIMARY KEY NOT NULL, LINEITEMSLIST_ORDER INT, QUANTITY INT , FK_FOR_PRODUCT_TABLE VARCHAR(255) , FK1_FOR_ORDER_TABLE VARCHAR(255) );

ALTER TABLE PHONE_TABLE ADD CONSTRAINT FK_FOR_ADDRESS FOREIGN KEY (FK_FOR_ADDRESS) REFERENCES ADDRESS (ID) ;

ALTER TABLE ALIAS_TABLE ADD CONSTRAINT FK1_FOR_CUSTOMER FOREIGN KEY (FK1_FOR_CUSTOMER_TABLE) REFERENCES CUSTOMER_TABLE (ID) ;

ALTER TABLE ALIAS_TABLE ADD CONSTRAINT FK2_FOR_CUSTOMER FOREIGN KEY (FK2_FOR_CUSTOMER_TABLE) REFERENCES CUSTOMER_TABLE (ID) ;

ALTER TABLE CUSTOMER_TABLE ADD CONSTRAINT FK5_FOR_CUST FOREIGN KEY (FK5_FOR_CUSTOMER_TABLE) REFERENCES ADDRESS (ID) ;

ALTER TABLE CUSTOMER_TABLE ADD CONSTRAINT FK6_FOR_CUST FOREIGN KEY (FK6_FOR_CUSTOMER_TABLE) REFERENCES ADDRESS (ID) ;

ALTER TABLE FKS_ALIAS_CUSTOMER ADD CONSTRAINT FK_FOR_CUSTOMER FOREIGN KEY (FK_FOR_CUSTOMER_TABLE) REFERENCES CUSTOMER_TABLE (ID) ;

ALTER TABLE FKS_ALIAS_CUSTOMER ADD CONSTRAINT FK_FOR_ALIAS FOREIGN KEY (FK_FOR_ALIAS_TABLE) REFERENCES ALIAS_TABLE (ID) ;

ALTER TABLE FKS_ANOOP_CNOOP  add constraint FK2_ALIAS Foreign Key (FK2_FOR_ALIAS_TABLE) references ALIAS_TABLE(id) ;

ALTER TABLE FKS_ANOOP_CNOOP  add constraint FK8_CUSTOMER Foreign Key (FK8_FOR_CUSTOMER_TABLE) references CUSTOMER_TABLE(id) ; 

ALTER TABLE CREDITCARD_TABLE ADD CONSTRAINT FK3_FOR_CUST FOREIGN KEY (FK3_FOR_CUSTOMER_TABLE) REFERENCES CUSTOMER_TABLE (ID) ;

ALTER TABLE CREDITCARD_TABLE ADD CONSTRAINT FK_FOR_ORDER FOREIGN KEY (FK_FOR_ORDER_TABLE) REFERENCES ORDER_TABLE (ID) ;

ALTER TABLE ORDER_TABLE ADD CONSTRAINT FK4_FOR_CUST FOREIGN KEY (FK4_FOR_CUSTOMER_TABLE) REFERENCES CUSTOMER_TABLE (ID) ;

ALTER TABLE ORDER_TABLE ADD CONSTRAINT FK0_FOR_LINEITEM FOREIGN KEY (FK0_FOR_LINEITEM_TABLE) REFERENCES LINEITEM_TABLE (ID) ;

ALTER TABLE LINEITEM_TABLE ADD CONSTRAINT FK_FOR_PRODUCT FOREIGN KEY (FK_FOR_PRODUCT_TABLE) REFERENCES PRODUCT_TABLE (ID) ;

ALTER TABLE LINEITEM_TABLE ADD CONSTRAINT FK1_FOR_ORDER FOREIGN KEY (FK1_FOR_ORDER_TABLE) REFERENCES ORDER_TABLE (ID) ;

ALTER TABLE SPOUSE_TABLE add constraint FK7_CUSTOMERTAB Foreign Key (FK7_FOR_CUSTOMER_TABLE) references CUSTOMER_TABLE(ID) ;

ALTER TABLE SPOUSE_TABLE add constraint FK_INFOTAB Foreign Key (FK_FOR_INFO_TABLE) references INFO_TABLE(ID) ; 

ALTER TABLE INFO_TABLE add constraint FK_SPOUSETAB Foreign Key (FK_FOR_SPOUSE_TABLE) references SPOUSE_TABLE(ID) ; 

CREATE TABLE EMPLOYEE (ID INT NOT NULL, FIRSTNAME VARCHAR(255) , LASTNAME VARCHAR(255), HIREDATE DATE, SALARY REAL NOT NULL, STATUS VARCHAR(255), THEORDERCOLUMN INT, EMPLOYEES_ORDER INT, FK_MGR INT, FK_DEPT INT, FK_PROJECT INT , FK_INS INT, CONSTRAINT PK_EMPLOYEE PRIMARY KEY (ID)) ;

CREATE TABLE DEPARTMENT (NAME VARCHAR(255) , ID INT NOT NULL, COMPANY_COMPANYID INT, CONSTRAINT PK_DEPARTMENT PRIMARY KEY (ID)) ;

CREATE TABLE PARTTIMEEMPLOYEE (ID INT NOT NULL, FIRSTNAME VARCHAR(255) , LASTNAME VARCHAR(255), HIREDATE DATE, SALARY REAL NOT NULL,  ADDRESS_ID VARCHAR(255), STATUS VARCHAR(255), FK_DEPT2 INT , FK_PROJECT INT, CONSTRAINT PK_PARTTIMEEMPLOYEE PRIMARY KEY (ID)) ;
ALTER TABLE PARTTIMEEMPLOYEE ADD CONSTRAINT FK_ADDR FOREIGN KEY (ADDRESS_ID) REFERENCES ADDRESS (ID) ;

ALTER TABLE PARTTIMEEMPLOYEE ADD CONSTRAINT FK_DEPT2 FOREIGN KEY (FK_DEPT2) REFERENCES DEPARTMENT (ID) ;

CREATE TABLE INSURANCE (INSID INT NOT NULL, CARRIER VARCHAR(255) , CONSTRAINT PK_INSURANCE PRIMARY KEY (INSID)) ;

CREATE TABLE COFFEE (ID INT NOT NULL, BRANDNAME VARCHAR(25), PRICE REAL, CONSTRAINT PK_COFFEE PRIMARY KEY (ID));

CREATE TABLE COMPANY (COMPANYID INT NOT NULL, NAME VARCHAR(25), ADDRESS_ID VARCHAR(255), CONSTRAINT PK_COMPANY PRIMARY KEY (COMPANYID));

ALTER TABLE COMPANY ADD CONSTRAINT FK_ADDRESS FOREIGN KEY (ADDRESS_ID) REFERENCES ADDRESS (ID) ;

ALTER TABLE DEPARTMENT ADD CONSTRAINT FK_COMPANY FOREIGN KEY (COMPANY_COMPANYID) REFERENCES COMPANY (COMPANYID) ;

CREATE TABLE DEPARTMENT2 (ID INT NOT NULL, NAME VARCHAR(255), CONSTRAINT PK_DEPARTMENT2 PRIMARY KEY (ID)) ;

CREATE TABLE TEAM (NAME VARCHAR(255) NOT NULL, TEAMID INT NOT NULL,  COMPANY_COMPANYID INT, CONSTRAINT PK_TEAM PRIMARY KEY (TEAMID));

ALTER TABLE TEAM ADD CONSTRAINT COMPANY_COMPANYID FOREIGN KEY (COMPANY_COMPANYID) REFERENCES COMPANY(COMPANYID);

CREATE TABLE ANNUALREVIEW (AID INT NOT NULL, SERVICE INT, CONSTRAINT PK_ANNUAL PRIMARY KEY (AID));

CREATE TABLE PERSON (PERSONID INT NOT NULL, FIRSTNAME VARCHAR(255) , LASTNAME VARCHAR(255) , PROJECT_PROJID INT , INSURANCE_INSID INT , TEAM_TEAMID INT , CONSTRAINT PK_PERSON PRIMARY KEY (PERSONID)) ;

CREATE TABLE PROJECT (PROJID INT NOT NULL, NAME VARCHAR(25), BUDGET DECIMAL(18,0), CONSTRAINT PK_PROJECT PRIMARY KEY (PROJID));

CREATE TABLE PROJECT_PERSON (PROJECTS_PROJID INT , PERSONS_PERSONID INT );

CREATE TABLE PERSON_INSURANCE (PERSON_PERSONID INT, INSURANCE_INSID INT );

CREATE TABLE PERSON_ANNUALREVIEW (PERSON_PERSONID INT, ANNUALREVIEWS_AID INT );

ALTER TABLE EMPLOYEE ADD CONSTRAINT FK_MGR FOREIGN KEY (FK_MGR) REFERENCES EMPLOYEE (ID) ;
ALTER TABLE EMPLOYEE ADD CONSTRAINT FK_DEPT FOREIGN KEY (FK_DEPT) REFERENCES DEPARTMENT (ID) ;
ALTER TABLE EMPLOYEE ADD CONSTRAINT FK_PROJECT FOREIGN KEY (FK_PROJECT) REFERENCES PROJECT (PROJID) ;
ALTER TABLE EMPLOYEE ADD CONSTRAINT FK_INS FOREIGN KEY (FK_INS) REFERENCES INSURANCE (INSID) ;

ALTER TABLE PERSON ADD CONSTRAINT TEAM_TEAMID FOREIGN KEY (TEAM_TEAMID) REFERENCES TEAM(TEAMID);
ALTER TABLE PERSON ADD CONSTRAINT PROJECT_PROJID FOREIGN KEY (PROJECT_PROJID) REFERENCES PROJECT(PROJID); 
ALTER TABLE PERSON ADD CONSTRAINT INSURANCE_INSID FOREIGN KEY (INSURANCE_INSID) REFERENCES INSURANCE(INSID); 

ALTER TABLE PROJECT_PERSON ADD CONSTRAINT PROJ_PROJID Foreign Key (PROJECTS_PROJID) references PROJECT(PROJID); 
ALTER TABLE PROJECT_PERSON ADD CONSTRAINT PERSONS_PERSONID Foreign Key (PERSONS_PERSONID) references PERSON(PERSONID); 


ALTER TABLE PERSON_ANNUALREVIEW ADD CONSTRAINT ANNUALREVIEWS_AID Foreign Key (ANNUALREVIEWS_AID) references ANNUALREVIEW(AID);
ALTER TABLE PERSON_ANNUALREVIEW ADD CONSTRAINT PERSON_PERSONID Foreign Key (PERSON_PERSONID) references PERSON(PERSONID);

ALTER TABLE PERSON_INSURANCE ADD CONSTRAINT P_PERSONID Foreign Key (PERSON_PERSONID) references PERSON(PERSONID); 
ALTER TABLE PERSON_INSURANCE ADD CONSTRAINT INS_INSID Foreign Key (INSURANCE_INSID) references INSURANCE(INSID);

CREATE TABLE BEANEJB_1X1_BI_BTOB ( ID VARCHAR(255)   PRIMARY KEY NOT NULL, NAME VARCHAR(255) , VALUE DECIMAL(18,0) NOT NULL, FK1_FOR_AEJB_1X1_BI_BTOB VARCHAR(255) , FK2_FOR_AEJB_1X1_BI_BTOB VARCHAR(255) , FK1_FOR_BEJB_1X1_BI_BTOB VARCHAR(255) , FK2_FOR_BEJB_1X1_BI_BTOB VARCHAR(255) );

CREATE TABLE BEJB_1X1_BI_BTOB ( ID VARCHAR(255)   PRIMARY KEY NOT NULL, NAME VARCHAR(255) , VALUE DECIMAL(18,0) NOT NULL, FK_FOR_AEJB_1X1_BI_BTOB VARCHAR(255) );

CREATE TABLE AEJB_1X1_BI_BTOB ( ID VARCHAR(255)   PRIMARY KEY NOT NULL, NAME VARCHAR(255) , VALUE DECIMAL(18,0) NOT NULL);


CREATE TABLE A_BASIC ( ID VARCHAR(255)   PRIMARY KEY NOT NULL, NAME VARCHAR(255) , VALUE INT, BASICINTEGER INT, BASICSHORT SMALLINT, BASICBIGSHORT SMALLINT, BASICFLOAT FLOAT, BASICBIGFLOAT FLOAT, BASICLONG BIGINT, BASICBIGLONG BIGINT, BASICDOUBLE DOUBLE, BASICBIGDOUBLE DOUBLE, BASICCHAR CHAR, BASICCHARARRAY VARCHAR(448), BASICBIGCHARARRAY VARCHAR(448), BASICBYTEARRAY  LONG VARCHAR FOR BIT DATA, BASICBIGBYTEARRAY LONG VARCHAR FOR BIT DATA, BASICBIGINTEGER DECIMAL(18,0), BASICBIGDECIMAL DECIMAL(18,0), BASICDATE DATE, BASICTIME TIME, BASICCALENDAR DATE, BASICTIMESTAMP TIMESTAMP ); 

CREATE TABLE DATES_TABLE (ID VARCHAR(255), dates_ORDER INT, DATES VARCHAR(255), FK_FOR_DATES_TABLE VARCHAR(255));
ALTER TABLE DATES_TABLE ADD CONSTRAINT FK_FOR_DATES_TABLE FOREIGN KEY (FK_FOR_DATES_TABLE) REFERENCES A_BASIC (ID) ;

CREATE TABLE DATE_TABLE (ID DATE, STRINGVERSION VARCHAR(255)) ;

CREATE TABLE A_BIGINTEGER ( ID VARCHAR(255), NAME VARCHAR(255) , VALUE INT, BASICINTEGER INT, BASICSHORT SMALLINT, BASICBIGSHORT SMALLINT, BASICFLOAT FLOAT, BASICBIGFLOAT FLOAT, BASICLONG BIGINT, BASICBIGLONG BIGINT, BASICDOUBLE DOUBLE, BASICBIGDOUBLE DOUBLE, BASICCHAR CHAR, BASICCHARARRAY VARCHAR(448), BASICBIGCHARARRAY VARCHAR(448), BASICBYTEARRAY  LONG VARCHAR FOR BIT DATA, BASICBIGBYTEARRAY LONG VARCHAR FOR BIT DATA, BASICBIGINTEGER DECIMAL(18,0) PRIMARY KEY NOT NULL, BASICBIGDECIMAL DECIMAL(18,0), BASICDATE DATE, BASICTIME TIME, BASICCALENDAR DATE, BASICTIMESTAMP TIMESTAMP ); 

CREATE TABLE A_BIGDECIMAL ( ID VARCHAR(255), NAME VARCHAR(255) , VALUE INT, BASICINTEGER INT, BASICSHORT SMALLINT, BASICBIGSHORT SMALLINT, BASICFLOAT FLOAT, BASICBIGFLOAT FLOAT, BASICLONG BIGINT, BASICBIGLONG BIGINT, BASICDOUBLE DOUBLE, BASICBIGDOUBLE DOUBLE, BASICCHAR CHAR, BASICCHARARRAY VARCHAR(448), BASICBIGCHARARRAY VARCHAR(448), BASICBYTEARRAY  LONG VARCHAR FOR BIT DATA, BASICBIGBYTEARRAY LONG VARCHAR FOR BIT DATA, BASICBIGINTEGER DECIMAL(18,0), BASICBIGDECIMAL DECIMAL(18,0) PRIMARY KEY NOT NULL, BASICDATE DATE, BASICTIME TIME, BASICCALENDAR DATE, BASICTIMESTAMP TIMESTAMP ); 

ALTER TABLE BEANEJB_1X1_BI_BTOB ADD CONSTRAINT FK1_FOR_AEJB_1X1_B FOREIGN KEY (FK1_FOR_AEJB_1X1_BI_BTOB) REFERENCES AEJB_1X1_BI_BTOB (ID) ;

ALTER TABLE BEANEJB_1X1_BI_BTOB ADD CONSTRAINT FK2_FOR_AEJB_1X1_B FOREIGN KEY (FK2_FOR_AEJB_1X1_BI_BTOB) REFERENCES AEJB_1X1_BI_BTOB (ID) ;

ALTER TABLE BEANEJB_1X1_BI_BTOB ADD CONSTRAINT FK1_FOR_BEJB_1X1_B FOREIGN KEY (FK1_FOR_BEJB_1X1_BI_BTOB) REFERENCES BEJB_1X1_BI_BTOB (ID) ;

ALTER TABLE BEANEJB_1X1_BI_BTOB ADD CONSTRAINT FK2_FOR_BEJB_1X1_B FOREIGN KEY (FK2_FOR_BEJB_1X1_BI_BTOB) REFERENCES BEJB_1X1_BI_BTOB (ID) ;

ALTER TABLE BEJB_1X1_BI_BTOB ADD CONSTRAINT FK_FOR_AEJB_1X1_BI FOREIGN KEY (FK_FOR_AEJB_1X1_BI_BTOB) REFERENCES AEJB_1X1_BI_BTOB (ID) ;

CREATE TABLE BEANEJB_1X1_BI_CASCADE ( ID VARCHAR(255)   PRIMARY KEY NOT NULL, NAME VARCHAR(255) , VALUE DECIMAL(18,0) NOT NULL, FK1_FOR_AEJB_1X1_BI_CASCADE VARCHAR(255) , FK2_FOR_AEJB_1X1_BI_CASCADE VARCHAR(255) , FK1_FOR_BEJB_1X1_BI_CASCADE VARCHAR(255) , FK2_FOR_BEJB_1X1_BI_CASCADE VARCHAR(255) );

CREATE TABLE BEJB_1X1_BI_CASCADE ( ID VARCHAR(255)   PRIMARY KEY NOT NULL, NAME VARCHAR(255) , VALUE DECIMAL(18,0) NOT NULL, FK_FOR_AEJB_1X1_BI_CASCADE VARCHAR(255) );

CREATE TABLE AEJB_1X1_BI_CASCADE ( ID VARCHAR(255)   PRIMARY KEY NOT NULL, NAME VARCHAR(255) , VALUE DECIMAL(18,0) NOT NULL);

ALTER TABLE BEANEJB_1X1_BI_CASCADE ADD CONSTRAINT FK1_FOR_AEJB_1X1_1 FOREIGN KEY (FK1_FOR_AEJB_1X1_BI_CASCADE) REFERENCES AEJB_1X1_BI_CASCADE (ID) ;

ALTER TABLE BEANEJB_1X1_BI_CASCADE ADD CONSTRAINT FK2_FOR_AEJB_1X1_1 FOREIGN KEY (FK2_FOR_AEJB_1X1_BI_CASCADE) REFERENCES AEJB_1X1_BI_CASCADE (ID) ;

ALTER TABLE BEANEJB_1X1_BI_CASCADE ADD CONSTRAINT FK1_FOR_BEJB_1X1_1 FOREIGN KEY (FK1_FOR_BEJB_1X1_BI_CASCADE) REFERENCES BEJB_1X1_BI_CASCADE (ID) ;

ALTER TABLE BEANEJB_1X1_BI_CASCADE ADD CONSTRAINT FK2_FOR_BEJB_1X1_1 FOREIGN KEY (FK2_FOR_BEJB_1X1_BI_CASCADE) REFERENCES BEJB_1X1_BI_CASCADE (ID) ;

ALTER TABLE BEJB_1X1_BI_CASCADE ADD CONSTRAINT FK_FOR_AEJB_1X1_B1 FOREIGN KEY (FK_FOR_AEJB_1X1_BI_CASCADE) REFERENCES AEJB_1X1_BI_CASCADE (ID) ;

CREATE TABLE BEANEJB_1X1_UNI_BTOB ( ID VARCHAR(255)   PRIMARY KEY NOT NULL, NAME VARCHAR(255) , VALUE DECIMAL(18,0) NOT NULL, FK1_FOR_AEJB_1X1_UNI_BTOB VARCHAR(255) , FK2_FOR_AEJB_1X1_UNI_BTOB VARCHAR(255) , FK1_FOR_BEJB_1X1_UNI_BTOB VARCHAR(255) , FK2_FOR_BEJB_1X1_UNI_BTOB VARCHAR(255) );

CREATE TABLE BEJB_1X1_UNI_BTOB ( ID VARCHAR(255)   PRIMARY KEY NOT NULL, NAME VARCHAR(255) , VALUE DECIMAL(18,0) NOT NULL, FK_FOR_AEJB_1X1_UNI_BTOB VARCHAR(255) );

CREATE TABLE AEJB_1X1_UNI_BTOB ( ID VARCHAR(255)   PRIMARY KEY NOT NULL, NAME VARCHAR(255) , VALUE DECIMAL(18,0) NOT NULL);

ALTER TABLE BEANEJB_1X1_UNI_BTOB ADD CONSTRAINT FK1_FOR_AEJB_1X1_U FOREIGN KEY (FK1_FOR_AEJB_1X1_UNI_BTOB) REFERENCES AEJB_1X1_UNI_BTOB (ID) ;

ALTER TABLE BEANEJB_1X1_UNI_BTOB ADD CONSTRAINT FK2_FOR_AEJB_1X1_U FOREIGN KEY (FK2_FOR_AEJB_1X1_UNI_BTOB) REFERENCES AEJB_1X1_UNI_BTOB (ID) ;

ALTER TABLE BEANEJB_1X1_UNI_BTOB ADD CONSTRAINT FK1_FOR_BEJB_1X1_U FOREIGN KEY (FK1_FOR_BEJB_1X1_UNI_BTOB) REFERENCES BEJB_1X1_UNI_BTOB (ID) ;

ALTER TABLE BEANEJB_1X1_UNI_BTOB ADD CONSTRAINT FK2_FOR_BEJB_1X1_U FOREIGN KEY (FK2_FOR_BEJB_1X1_UNI_BTOB) REFERENCES BEJB_1X1_UNI_BTOB (ID) ;

ALTER TABLE BEJB_1X1_UNI_BTOB ADD CONSTRAINT FK_FOR_AEJB_1X1_UN FOREIGN KEY (FK_FOR_AEJB_1X1_UNI_BTOB) REFERENCES AEJB_1X1_UNI_BTOB (ID) ;

CREATE TABLE BEANEJB_1XM_BI_BTOB ( ID VARCHAR(255)   PRIMARY KEY NOT NULL, NAME VARCHAR(255) , VALUE DECIMAL(18,0) NOT NULL, FK1_FOR_AEJB_1XM_BI_BTOB VARCHAR(255) , FK2_FOR_AEJB_1XM_BI_BTOB VARCHAR(255) , FK1_FOR_BEJB_1XM_BI_BTOB VARCHAR(255) , FK2_FOR_BEJB_1XM_BI_BTOB VARCHAR(255) , FK3_FOR_BEJB_1XM_BI_BTOB VARCHAR(255) , FK4_FOR_BEJB_1XM_BI_BTOB VARCHAR(255) );

CREATE TABLE BEJB_1XM_BI_BTOB ( ID VARCHAR(255)   PRIMARY KEY NOT NULL, bCol_ORDER INT, NAME VARCHAR(255) , VALUE DECIMAL(18,0) NOT NULL, FK_FOR_AEJB_1XM_BI_BTOB VARCHAR(255) );

CREATE TABLE BNE_1XM_BI_BTOB ( ID VARCHAR(255)   PRIMARY KEY NOT NULL, NAME VARCHAR(255) , VALUE DECIMAL(18,0) NOT NULL, STREET VARCHAR(255), CITY VARCHAR(255), STATE VARCHAR(255), ZIP VARCHAR(255), PLUSFOUR VARCHAR(255), FK_FOR_ANE_1XM_BI_BTOB VARCHAR(255) );

CREATE TABLE B_EMBEDDABLE ( ID VARCHAR(255)   PRIMARY KEY NOT NULL, NAME VARCHAR(255) , VALUE DECIMAL(18,0) NOT NULL, STREET VARCHAR(255), CITY VARCHAR(255), STATE VARCHAR(255), ZIP VARCHAR(255), PLUSFOUR VARCHAR(255));

CREATE TABLE AEJB_1XM_BI_BTOB ( ID VARCHAR(255)   PRIMARY KEY NOT NULL, NAME VARCHAR(255) , VALUE DECIMAL(18,0) NOT NULL);

CREATE TABLE ANE_1XM_BI_BTOB ( ID VARCHAR(255)   PRIMARY KEY NOT NULL, NAME VARCHAR(255) , VALUE DECIMAL(18,0) NOT NULL );

CREATE TABLE A_ADDRESS ( A_ID VARCHAR(255) NOT NULL,  STREET VARCHAR(30), CITY VARCHAR(30), STATE VARCHAR(2), ZIP VARCHAR(10) );

CREATE TABLE COLTAB_ADDRESS ( A_ID VARCHAR(255) NOT NULL,  STREET VARCHAR(30), CITY VARCHAR(30), STATE VARCHAR(2), ZIP VARCHAR(10) );

CREATE TABLE AEC ( ID VARCHAR(255)   PRIMARY KEY NOT NULL, NAME VARCHAR(255) , VALUE DECIMAL(18,0) );

CREATE TABLE COLTAB ( ID VARCHAR(255)   PRIMARY KEY NOT NULL, NAME VARCHAR(255) , VALUE DECIMAL(18,0) );


ALTER TABLE BEANEJB_1XM_BI_BTOB ADD CONSTRAINT FK1_FOR_AEJB_1XM_B FOREIGN KEY (FK1_FOR_AEJB_1XM_BI_BTOB) REFERENCES AEJB_1XM_BI_BTOB (ID) ;

ALTER TABLE BEANEJB_1XM_BI_BTOB ADD CONSTRAINT FK2_FOR_AEJB_1XM_B FOREIGN KEY (FK2_FOR_AEJB_1XM_BI_BTOB) REFERENCES AEJB_1XM_BI_BTOB (ID) ;

ALTER TABLE BEANEJB_1XM_BI_BTOB ADD CONSTRAINT FK1_FOR_BEJB_1XM_B FOREIGN KEY (FK1_FOR_BEJB_1XM_BI_BTOB) REFERENCES BEJB_1XM_BI_BTOB (ID) ;

ALTER TABLE BEANEJB_1XM_BI_BTOB ADD CONSTRAINT FK2_FOR_BEJB_1XM_B FOREIGN KEY (FK2_FOR_BEJB_1XM_BI_BTOB) REFERENCES BEJB_1XM_BI_BTOB (ID) ;

ALTER TABLE BEANEJB_1XM_BI_BTOB ADD CONSTRAINT FK3_FOR_BEJB_1XM_B FOREIGN KEY (FK3_FOR_BEJB_1XM_BI_BTOB) REFERENCES BEJB_1XM_BI_BTOB (ID) ;

ALTER TABLE BEANEJB_1XM_BI_BTOB ADD CONSTRAINT FK4_FOR_BEJB_1XM_B FOREIGN KEY (FK4_FOR_BEJB_1XM_BI_BTOB) REFERENCES BEJB_1XM_BI_BTOB (ID) ;

ALTER TABLE BEJB_1XM_BI_BTOB ADD CONSTRAINT FK_FOR_AEJB_1XM_BI FOREIGN KEY (FK_FOR_AEJB_1XM_BI_BTOB) REFERENCES AEJB_1XM_BI_BTOB (ID) ;

ALTER TABLE BNE_1XM_BI_BTOB ADD CONSTRAINT FK_FOR_ANE_1XM_BI FOREIGN KEY (FK_FOR_ANE_1XM_BI_BTOB) REFERENCES ANE_1XM_BI_BTOB (ID) ;

CREATE TABLE BEANEJB_1XM_BI_CASCADE ( ID VARCHAR(255)   PRIMARY KEY NOT NULL, NAME VARCHAR(255) , VALUE DECIMAL(18,0) NOT NULL, FK1_FOR_AEJB_1XM_BI_CASCADE VARCHAR(255) , FK2_FOR_AEJB_1XM_BI_CASCADE VARCHAR(255) , FK1_FOR_BEJB_1XM_BI_CASCADE VARCHAR(255) , FK2_FOR_BEJB_1XM_BI_CASCADE VARCHAR(255) );

CREATE TABLE BEJB_1XM_BI_CASCADE ( ID VARCHAR(255)   PRIMARY KEY NOT NULL, NAME VARCHAR(255) , VALUE DECIMAL(18,0) NOT NULL, FK_FOR_AEJB_1XM_BI_CASCADE VARCHAR(255) );

CREATE TABLE AEJB_1XM_BI_CASCADE ( ID VARCHAR(255)   PRIMARY KEY NOT NULL, NAME VARCHAR(255) , VALUE DECIMAL(18,0) NOT NULL);

ALTER TABLE BEANEJB_1XM_BI_CASCADE ADD CONSTRAINT FK1_FOR_AEJB_1XM_1 FOREIGN KEY (FK1_FOR_AEJB_1XM_BI_CASCADE) REFERENCES AEJB_1XM_BI_CASCADE (ID) ;

ALTER TABLE BEANEJB_1XM_BI_CASCADE ADD CONSTRAINT FK2_FOR_AEJB_1XM_1 FOREIGN KEY (FK2_FOR_AEJB_1XM_BI_CASCADE) REFERENCES AEJB_1XM_BI_CASCADE (ID) ;

ALTER TABLE BEANEJB_1XM_BI_CASCADE ADD CONSTRAINT FK1_FOR_BEJB_1XM_1 FOREIGN KEY (FK1_FOR_BEJB_1XM_BI_CASCADE) REFERENCES BEJB_1XM_BI_CASCADE (ID) ;

ALTER TABLE BEANEJB_1XM_BI_CASCADE ADD CONSTRAINT FK2_FOR_BEJB_1XM_1 FOREIGN KEY (FK2_FOR_BEJB_1XM_BI_CASCADE) REFERENCES BEJB_1XM_BI_CASCADE (ID) ;

ALTER TABLE BEJB_1XM_BI_CASCADE ADD CONSTRAINT FK_FOR_AEJB_1XM_B1 FOREIGN KEY (FK_FOR_AEJB_1XM_BI_CASCADE) REFERENCES AEJB_1XM_BI_CASCADE (ID) ;

CREATE TABLE BEANEJB_1XM_BI_DELETE ( ID VARCHAR(255)   PRIMARY KEY NOT NULL, NAME VARCHAR(255) , VALUE DECIMAL(18,0) NOT NULL, FK1_FOR_AEJB_1XM_BI_DELETE VARCHAR(255) , FK2_FOR_AEJB_1XM_BI_DELETE VARCHAR(255) , FK1_FOR_BEJB_1XM_BI_DELETE VARCHAR(255) , FK2_FOR_BEJB_1XM_BI_DELETE VARCHAR(255) );

CREATE TABLE BEJB_1XM_BI_DELETE ( ID VARCHAR(255)   PRIMARY KEY NOT NULL, NAME VARCHAR(255) , VALUE DECIMAL(18,0) NOT NULL, FK_FOR_AEJB_1XM_BI_DELETE VARCHAR(255) );

CREATE TABLE AEJB_1XM_BI_DELETE ( ID VARCHAR(255)   PRIMARY KEY NOT NULL, NAME VARCHAR(255) , VALUE DECIMAL(18,0) NOT NULL);

ALTER TABLE BEANEJB_1XM_BI_DELETE ADD CONSTRAINT FK1_FOR_AEJB_1XM_2 FOREIGN KEY (FK1_FOR_AEJB_1XM_BI_DELETE) REFERENCES AEJB_1XM_BI_DELETE (ID) ;

ALTER TABLE BEANEJB_1XM_BI_DELETE ADD CONSTRAINT FK2_FOR_AEJB_1XM_2 FOREIGN KEY (FK2_FOR_AEJB_1XM_BI_DELETE) REFERENCES AEJB_1XM_BI_DELETE (ID) ;

ALTER TABLE BEANEJB_1XM_BI_DELETE ADD CONSTRAINT FK1_FOR_BEJB_1XM_2 FOREIGN KEY (FK1_FOR_BEJB_1XM_BI_DELETE) REFERENCES BEJB_1XM_BI_DELETE (ID) ;

ALTER TABLE BEANEJB_1XM_BI_DELETE ADD CONSTRAINT FK2_FOR_BEJB_1XM_2 FOREIGN KEY (FK2_FOR_BEJB_1XM_BI_DELETE) REFERENCES BEJB_1XM_BI_DELETE (ID) ;

ALTER TABLE BEJB_1XM_BI_DELETE ADD CONSTRAINT FK_FOR_AEJB_1XM_B2 FOREIGN KEY (FK_FOR_AEJB_1XM_BI_DELETE) REFERENCES AEJB_1XM_BI_DELETE (ID) ;

CREATE TABLE BEANEJB_1XM_UNI_BTOB ( ID VARCHAR(255)   PRIMARY KEY NOT NULL, NAME VARCHAR(255) , VALUE DECIMAL(18,0) NOT NULL, FK1_FOR_AEJB_1XM_UNI_BTOB VARCHAR(255) , FK2_FOR_AEJB_1XM_UNI_BTOB VARCHAR(255) , FK1_FOR_BEJB_1XM_UNI_BTOB VARCHAR(255) , FK2_FOR_BEJB_1XM_UNI_BTOB VARCHAR(255), FK3_FOR_BEJB_1XM_UNI_BTOB VARCHAR(255) , FK4_FOR_BEJB_1XM_UNI_BTOB VARCHAR(255) );

CREATE TABLE BEJB_1XM_UNI_BTOB ( ID VARCHAR(255)   PRIMARY KEY NOT NULL, NAME VARCHAR(255) , VALUE DECIMAL(18,0) NOT NULL, FK_FOR_AEJB_1XM_UNI_BTOB VARCHAR(255) );

CREATE TABLE AEJB_1XM_UNI_BTOB ( ID VARCHAR(255)   PRIMARY KEY NOT NULL, NAME VARCHAR(255) , VALUE DECIMAL(18,0) NOT NULL);

ALTER TABLE BEANEJB_1XM_UNI_BTOB ADD CONSTRAINT FK1_FOR_AEJB_1XM_U FOREIGN KEY (FK1_FOR_AEJB_1XM_UNI_BTOB) REFERENCES AEJB_1XM_UNI_BTOB (ID) ;

ALTER TABLE BEANEJB_1XM_UNI_BTOB ADD CONSTRAINT FK2_FOR_AEJB_1XM_U FOREIGN KEY (FK2_FOR_AEJB_1XM_UNI_BTOB) REFERENCES AEJB_1XM_UNI_BTOB (ID) ;

ALTER TABLE BEANEJB_1XM_UNI_BTOB ADD CONSTRAINT FK1_FOR_BEJB_1XM_U FOREIGN KEY (FK1_FOR_BEJB_1XM_UNI_BTOB) REFERENCES BEJB_1XM_UNI_BTOB (ID) ;

ALTER TABLE BEANEJB_1XM_UNI_BTOB ADD CONSTRAINT FK2_FOR_BEJB_1XM_U FOREIGN KEY (FK2_FOR_BEJB_1XM_UNI_BTOB) REFERENCES BEJB_1XM_UNI_BTOB (ID) ;

ALTER TABLE BEANEJB_1XM_UNI_BTOB ADD CONSTRAINT FK3_FOR_BEJB_1XM_U FOREIGN KEY (FK3_FOR_BEJB_1XM_UNI_BTOB) REFERENCES BEJB_1XM_UNI_BTOB (ID) ;

ALTER TABLE BEANEJB_1XM_UNI_BTOB ADD CONSTRAINT FK4_FOR_BEJB_1XM_U FOREIGN KEY (FK4_FOR_BEJB_1XM_UNI_BTOB) REFERENCES BEJB_1XM_UNI_BTOB (ID) ;

CREATE TABLE BEANEJB_MX1_UNI_BTOB ( ID VARCHAR(255)   PRIMARY KEY NOT NULL, NAME VARCHAR(255) , VALUE DECIMAL(18,0) NOT NULL, FK1_FOR_AEJB_MX1_UNI_BTOB VARCHAR(255) , FK2_FOR_AEJB_MX1_UNI_BTOB VARCHAR(255) , FK1_FOR_BEJB_MX1_UNI_BTOB VARCHAR(255) , FK2_FOR_BEJB_MX1_UNI_BTOB VARCHAR(255) ,
FK3_FOR_BEJB_MX1_UNI_BTOB VARCHAR(255) , FK4_FOR_BEJB_MX1_UNI_BTOB VARCHAR(255) );

CREATE TABLE BEJB_MX1_UNI_BTOB ( ID VARCHAR(255)   PRIMARY KEY NOT NULL, NAME VARCHAR(255) , VALUE DECIMAL(18,0) NOT NULL, FK_FOR_AEJB_MX1_UNI_BTOB VARCHAR(255) );

CREATE TABLE AEJB_MX1_UNI_BTOB ( ID VARCHAR(255)   PRIMARY KEY NOT NULL, NAME VARCHAR(255) , VALUE DECIMAL(18,0) NOT NULL);

ALTER TABLE BEANEJB_MX1_UNI_BTOB ADD CONSTRAINT FK1_FOR_AEJB_MX1_U FOREIGN KEY (FK1_FOR_AEJB_MX1_UNI_BTOB) REFERENCES AEJB_MX1_UNI_BTOB (ID) ;

ALTER TABLE BEANEJB_MX1_UNI_BTOB ADD CONSTRAINT FK2_FOR_AEJB_MX1_U FOREIGN KEY (FK2_FOR_AEJB_MX1_UNI_BTOB) REFERENCES AEJB_MX1_UNI_BTOB (ID) ;

ALTER TABLE BEANEJB_MX1_UNI_BTOB ADD CONSTRAINT FK1_FOR_BEJB_MX1_U FOREIGN KEY (FK1_FOR_BEJB_MX1_UNI_BTOB) REFERENCES BEJB_MX1_UNI_BTOB (ID) ;

ALTER TABLE BEANEJB_MX1_UNI_BTOB ADD CONSTRAINT FK2_FOR_BEJB_MX1_U FOREIGN KEY (FK2_FOR_BEJB_MX1_UNI_BTOB) REFERENCES BEJB_MX1_UNI_BTOB (ID) ;

ALTER TABLE BEANEJB_MX1_UNI_BTOB ADD CONSTRAINT FK3_FOR_BEJB_MX1_U FOREIGN KEY (FK3_FOR_BEJB_MX1_UNI_BTOB) REFERENCES BEJB_MX1_UNI_BTOB (ID) ;

ALTER TABLE BEANEJB_MX1_UNI_BTOB ADD CONSTRAINT FK4_FOR_BEJB_MX1_U FOREIGN KEY (FK4_FOR_BEJB_MX1_UNI_BTOB) REFERENCES BEJB_MX1_UNI_BTOB (ID) ;

ALTER TABLE BEJB_MX1_UNI_BTOB ADD CONSTRAINT FK_FOR_AEJB_MX1_UN FOREIGN KEY (FK_FOR_AEJB_MX1_UNI_BTOB) REFERENCES AEJB_MX1_UNI_BTOB (ID) ;

CREATE TABLE BEANEJB_MX1_UNI_DELETE ( ID VARCHAR(255)   PRIMARY KEY NOT NULL, NAME VARCHAR(255) , VALUE DECIMAL(18,0) NOT NULL, FK1_FOR_AEJB_MX1_UNI_DELETE VARCHAR(255) , FK2_FOR_AEJB_MX1_UNI_DELETE VARCHAR(255) , FK1_FOR_BEJB_MX1_UNI_DELETE VARCHAR(255) , FK2_FOR_BEJB_MX1_UNI_DELETE VARCHAR(255) , FK3_FOR_BEJB_MX1_UNI_DELETE VARCHAR(255) , FK4_FOR_BEJB_MX1_UNI_DELETE VARCHAR(255) );

CREATE TABLE BEJB_MX1_UNI_DELETE ( ID VARCHAR(255)   PRIMARY KEY NOT NULL, NAME VARCHAR(255) , VALUE DECIMAL(18,0) NOT NULL, FK_FOR_AEJB_MX1_UNI_DELETE VARCHAR(255) );

CREATE TABLE AEJB_MX1_UNI_DELETE ( ID VARCHAR(255)   PRIMARY KEY NOT NULL, NAME VARCHAR(255) , VALUE DECIMAL(18,0) NOT NULL);

ALTER TABLE BEANEJB_MX1_UNI_DELETE ADD CONSTRAINT FK1_FOR_AEJB_MX1_1 FOREIGN KEY (FK1_FOR_AEJB_MX1_UNI_DELETE) REFERENCES AEJB_MX1_UNI_DELETE (ID) ;

ALTER TABLE BEANEJB_MX1_UNI_DELETE ADD CONSTRAINT FK2_FOR_AEJB_MX1_1 FOREIGN KEY (FK2_FOR_AEJB_MX1_UNI_DELETE) REFERENCES AEJB_MX1_UNI_DELETE (ID) ;

ALTER TABLE BEANEJB_MX1_UNI_DELETE ADD CONSTRAINT FK1_FOR_BEJB_MX1_1 FOREIGN KEY (FK1_FOR_BEJB_MX1_UNI_DELETE) REFERENCES BEJB_MX1_UNI_DELETE (ID) ;

ALTER TABLE BEANEJB_MX1_UNI_DELETE ADD CONSTRAINT FK2_FOR_BEJB_MX1_1 FOREIGN KEY (FK2_FOR_BEJB_MX1_UNI_DELETE) REFERENCES BEJB_MX1_UNI_DELETE (ID) ;

ALTER TABLE BEANEJB_MX1_UNI_DELETE ADD CONSTRAINT FK3_FOR_BEJB_MX1_1 FOREIGN KEY (FK3_FOR_BEJB_MX1_UNI_DELETE) REFERENCES BEJB_MX1_UNI_DELETE (ID) ;

ALTER TABLE BEANEJB_MX1_UNI_DELETE ADD CONSTRAINT FK4_FOR_BEJB_MX1_1 FOREIGN KEY (FK4_FOR_BEJB_MX1_UNI_DELETE) REFERENCES BEJB_MX1_UNI_DELETE (ID) ;

ALTER TABLE BEJB_MX1_UNI_DELETE ADD CONSTRAINT FK_FOR_AEJB_MX1_U1 FOREIGN KEY (FK_FOR_AEJB_MX1_UNI_DELETE) REFERENCES AEJB_MX1_UNI_DELETE (ID) ;

CREATE TABLE FKEYS_MXM_BI_BTOB ( FK_FOR_AEJB_MXM_BI_BTOB VARCHAR(255)  NOT NULL, FK_FOR_BEJB_MXM_BI_BTOB VARCHAR(255) );

CREATE TABLE BEANEJB_MXM_BI_BTOB ( ID VARCHAR(255)   PRIMARY KEY NOT NULL, NAME VARCHAR(255) , VALUE DECIMAL(18,0) NOT NULL, FK1_FOR_AEJB_MXM_BI_BTOB VARCHAR(255) , FK2_FOR_AEJB_MXM_BI_BTOB VARCHAR(255) , FK3_FOR_AEJB_MXM_BI_BTOB VARCHAR(255) , FK4_FOR_AEJB_MXM_BI_BTOB VARCHAR(255) , FK1_FOR_BEJB_MXM_BI_BTOB VARCHAR(255) , FK2_FOR_BEJB_MXM_BI_BTOB VARCHAR(255) , FK3_FOR_BEJB_MXM_BI_BTOB VARCHAR(255) , FK4_FOR_BEJB_MXM_BI_BTOB VARCHAR(255) );

CREATE TABLE AEJB_MXM_BI_BTOB ( ID VARCHAR(255)   PRIMARY KEY NOT NULL, NAME VARCHAR(255) , VALUE DECIMAL(18,0) NOT NULL);

CREATE TABLE BEJB_MXM_BI_BTOB ( ID VARCHAR(255)   PRIMARY KEY NOT NULL, NAME VARCHAR(255) , VALUE DECIMAL(18,0) NOT NULL);

ALTER TABLE BEANEJB_MXM_BI_BTOB ADD CONSTRAINT FK1_FOR_AEJB_MXM_B FOREIGN KEY (FK1_FOR_AEJB_MXM_BI_BTOB) REFERENCES AEJB_MXM_BI_BTOB (ID) ;

ALTER TABLE BEANEJB_MXM_BI_BTOB ADD CONSTRAINT FK2_FOR_AEJB_MXM_B FOREIGN KEY (FK2_FOR_AEJB_MXM_BI_BTOB) REFERENCES AEJB_MXM_BI_BTOB (ID) ;

ALTER TABLE BEANEJB_MXM_BI_BTOB ADD CONSTRAINT FK3_FOR_AEJB_MXM_B FOREIGN KEY (FK3_FOR_AEJB_MXM_BI_BTOB) REFERENCES AEJB_MXM_BI_BTOB (ID) ;

ALTER TABLE BEANEJB_MXM_BI_BTOB ADD CONSTRAINT FK4_FOR_AEJB_MXM_B FOREIGN KEY (FK4_FOR_AEJB_MXM_BI_BTOB) REFERENCES AEJB_MXM_BI_BTOB (ID) ;

ALTER TABLE BEANEJB_MXM_BI_BTOB ADD CONSTRAINT FK1_FOR_BEJB_MXM_B FOREIGN KEY (FK1_FOR_BEJB_MXM_BI_BTOB) REFERENCES BEJB_MXM_BI_BTOB (ID) ;

ALTER TABLE BEANEJB_MXM_BI_BTOB ADD CONSTRAINT FK2_FOR_BEJB_MXM_B FOREIGN KEY (FK2_FOR_BEJB_MXM_BI_BTOB) REFERENCES BEJB_MXM_BI_BTOB (ID) ;

ALTER TABLE BEANEJB_MXM_BI_BTOB ADD CONSTRAINT FK3_FOR_BEJB_MXM_B FOREIGN KEY (FK3_FOR_BEJB_MXM_BI_BTOB) REFERENCES BEJB_MXM_BI_BTOB (ID) ;

ALTER TABLE BEANEJB_MXM_BI_BTOB ADD CONSTRAINT FK4_FOR_BEJB_MXM_B FOREIGN KEY (FK4_FOR_BEJB_MXM_BI_BTOB) REFERENCES BEJB_MXM_BI_BTOB (ID) ;

ALTER TABLE FKEYS_MXM_BI_BTOB ADD CONSTRAINT FK_FOR_AEJB_MXM_BI FOREIGN KEY (FK_FOR_AEJB_MXM_BI_BTOB) REFERENCES AEJB_MXM_BI_BTOB (ID) ;

ALTER TABLE FKEYS_MXM_BI_BTOB ADD CONSTRAINT FK_FOR_BEJB_MXM_BI FOREIGN KEY (FK_FOR_BEJB_MXM_BI_BTOB) REFERENCES BEJB_MXM_BI_BTOB (ID) ;

CREATE TABLE BEANEJB_MXM_BI_DELETE ( ID VARCHAR(255)   PRIMARY KEY NOT NULL, NAME VARCHAR(255) , VALUE DECIMAL(18,0) NOT NULL, FK1_FOR_AEJB_MXM_BI_DELETE VARCHAR(255) , FK2_FOR_AEJB_MXM_BI_DELETE VARCHAR(255) , FK3_FOR_AEJB_MXM_BI_DELETE VARCHAR(255) , FK4_FOR_AEJB_MXM_BI_DELETE VARCHAR(255) , FK1_FOR_BEJB_MXM_BI_DELETE VARCHAR(255) , FK2_FOR_BEJB_MXM_BI_DELETE VARCHAR(255) , FK3_FOR_BEJB_MXM_BI_DELETE VARCHAR(255) , FK4_FOR_BEJB_MXM_BI_DELETE VARCHAR(255) );

CREATE TABLE FKEYS_MXM_BI_DELETE ( FK_FOR_AEJB_MXM_BI_DELETE VARCHAR(255)  NOT NULL, FK_FOR_BEJB_MXM_BI_DELETE VARCHAR(255) );

CREATE TABLE AEJB_MXM_BI_DELETE ( ID VARCHAR(255)   PRIMARY KEY NOT NULL, NAME VARCHAR(255) , VALUE DECIMAL(18,0) NOT NULL);

CREATE TABLE BEJB_MXM_BI_DELETE ( ID VARCHAR(255)   PRIMARY KEY NOT NULL, NAME VARCHAR(255) , VALUE DECIMAL(18,0) NOT NULL);


ALTER TABLE BEANEJB_MXM_BI_DELETE ADD CONSTRAINT FK1_FOR_AEJB_MXM_1 FOREIGN KEY (FK1_FOR_AEJB_MXM_BI_DELETE) REFERENCES AEJB_MXM_BI_DELETE (ID) ;

ALTER TABLE BEANEJB_MXM_BI_DELETE ADD CONSTRAINT FK2_FOR_AEJB_MXM_1 FOREIGN KEY (FK2_FOR_AEJB_MXM_BI_DELETE) REFERENCES AEJB_MXM_BI_DELETE (ID) ;

ALTER TABLE BEANEJB_MXM_BI_DELETE ADD CONSTRAINT FK3_FOR_AEJB_MXM_1 FOREIGN KEY (FK3_FOR_AEJB_MXM_BI_DELETE) REFERENCES AEJB_MXM_BI_DELETE (ID) ;

ALTER TABLE BEANEJB_MXM_BI_DELETE ADD CONSTRAINT FK4_FOR_AEJB_MXM_1 FOREIGN KEY (FK4_FOR_AEJB_MXM_BI_DELETE) REFERENCES AEJB_MXM_BI_DELETE (ID) ;

ALTER TABLE BEANEJB_MXM_BI_DELETE ADD CONSTRAINT FK1_FOR_BEJB_MXM_1 FOREIGN KEY (FK1_FOR_BEJB_MXM_BI_DELETE) REFERENCES BEJB_MXM_BI_DELETE (ID) ;

ALTER TABLE BEANEJB_MXM_BI_DELETE ADD CONSTRAINT FK2_FOR_BEJB_MXM_1 FOREIGN KEY (FK2_FOR_BEJB_MXM_BI_DELETE) REFERENCES BEJB_MXM_BI_DELETE (ID) ;

ALTER TABLE BEANEJB_MXM_BI_DELETE ADD CONSTRAINT FK3_FOR_BEJB_MXM_1 FOREIGN KEY (FK3_FOR_BEJB_MXM_BI_DELETE) REFERENCES BEJB_MXM_BI_DELETE (ID) ;

ALTER TABLE BEANEJB_MXM_BI_DELETE ADD CONSTRAINT FK4_FOR_BEJB_MXM_1 FOREIGN KEY (FK4_FOR_BEJB_MXM_BI_DELETE) REFERENCES BEJB_MXM_BI_DELETE (ID) ;

ALTER TABLE FKEYS_MXM_BI_DELETE ADD CONSTRAINT FK_FOR_AEJB_MXM_B1 FOREIGN KEY (FK_FOR_AEJB_MXM_BI_DELETE) REFERENCES AEJB_MXM_BI_DELETE (ID) ;

ALTER TABLE FKEYS_MXM_BI_DELETE ADD CONSTRAINT FK_FOR_BEJB_MXM_B1 FOREIGN KEY (FK_FOR_BEJB_MXM_BI_DELETE) REFERENCES BEJB_MXM_BI_DELETE (ID) ;

CREATE TABLE FKEYS_MXM_UNI_BTOB ( FK_FOR_AEJB_MXM_UNI_BTOB VARCHAR(255)  NOT NULL, FK_FOR_BEJB_MXM_UNI_BTOB VARCHAR(255) );

CREATE TABLE BEANEJB_MXM_UNI_BTOB ( ID VARCHAR(255)   PRIMARY KEY NOT NULL, NAME VARCHAR(255) , VALUE DECIMAL(18,0) NOT NULL, FK1_FOR_AEJB_MXM_UNI_BTOB VARCHAR(255) , FK2_FOR_AEJB_MXM_UNI_BTOB VARCHAR(255) , FK3_FOR_AEJB_MXM_UNI_BTOB VARCHAR(255) , FK4_FOR_AEJB_MXM_UNI_BTOB VARCHAR(255) , FK1_FOR_BEJB_MXM_UNI_BTOB VARCHAR(255) , FK2_FOR_BEJB_MXM_UNI_BTOB VARCHAR(255) , FK3_FOR_BEJB_MXM_UNI_BTOB VARCHAR(255) , FK4_FOR_BEJB_MXM_UNI_BTOB VARCHAR(255) );

CREATE TABLE AEJB_MXM_UNI_BTOB ( ID VARCHAR(255)   PRIMARY KEY NOT NULL, NAME VARCHAR(255) , VALUE DECIMAL(18,0) NOT NULL);

CREATE TABLE BEJB_MXM_UNI_BTOB ( ID VARCHAR(255)   PRIMARY KEY NOT NULL, NAME VARCHAR(255) , VALUE DECIMAL(18,0)  NOT NULL );

ALTER TABLE BEANEJB_MXM_UNI_BTOB ADD CONSTRAINT FK1_FOR_AEJB_MXM_U FOREIGN KEY (FK1_FOR_AEJB_MXM_UNI_BTOB) REFERENCES AEJB_MXM_UNI_BTOB (ID) ;

ALTER TABLE BEANEJB_MXM_UNI_BTOB ADD CONSTRAINT FK2_FOR_AEJB_MXM_U FOREIGN KEY (FK2_FOR_AEJB_MXM_UNI_BTOB) REFERENCES AEJB_MXM_UNI_BTOB (ID) ;

ALTER TABLE BEANEJB_MXM_UNI_BTOB ADD CONSTRAINT FK3_FOR_AEJB_MXM_U FOREIGN KEY (FK3_FOR_AEJB_MXM_UNI_BTOB) REFERENCES AEJB_MXM_UNI_BTOB (ID) ;

ALTER TABLE BEANEJB_MXM_UNI_BTOB ADD CONSTRAINT FK4_FOR_AEJB_MXM_U FOREIGN KEY (FK4_FOR_AEJB_MXM_UNI_BTOB) REFERENCES AEJB_MXM_UNI_BTOB (ID) ;

ALTER TABLE BEANEJB_MXM_UNI_BTOB ADD CONSTRAINT FK1_FOR_BEJB_MXM_U FOREIGN KEY (FK1_FOR_BEJB_MXM_UNI_BTOB) REFERENCES BEJB_MXM_UNI_BTOB (ID) ;

ALTER TABLE BEANEJB_MXM_UNI_BTOB ADD CONSTRAINT FK2_FOR_BEJB_MXM_U FOREIGN KEY (FK2_FOR_BEJB_MXM_UNI_BTOB) REFERENCES BEJB_MXM_UNI_BTOB (ID) ;

ALTER TABLE BEANEJB_MXM_UNI_BTOB ADD CONSTRAINT FK3_FOR_BEJB_MXM_U FOREIGN KEY (FK3_FOR_BEJB_MXM_UNI_BTOB) REFERENCES BEJB_MXM_UNI_BTOB (ID) ;

ALTER TABLE BEANEJB_MXM_UNI_BTOB ADD CONSTRAINT FK4_FOR_BEJB_MXM_U FOREIGN KEY (FK4_FOR_BEJB_MXM_UNI_BTOB) REFERENCES BEJB_MXM_UNI_BTOB (ID) ;

ALTER TABLE FKEYS_MXM_UNI_BTOB ADD CONSTRAINT FK_FOR_AEJB_MXM_UN FOREIGN KEY (FK_FOR_AEJB_MXM_UNI_BTOB) REFERENCES AEJB_MXM_UNI_BTOB (ID) ;

ALTER TABLE FKEYS_MXM_UNI_BTOB ADD CONSTRAINT FK_FOR_BEJB_MXM_UN FOREIGN KEY (FK_FOR_BEJB_MXM_UNI_BTOB) REFERENCES BEJB_MXM_UNI_BTOB (ID) ;

CREATE TABLE PKEY ( PMIDINTEGER INT  NOT NULL, PMIDSTRING VARCHAR(25) NOT NULL, PMIDFLOAT REAL NOT NULL, BRANDNAME VARCHAR(25) , PRICE REAL , CONSTRAINT PK_PKEY PRIMARY KEY (PMIDINTEGER, PMIDSTRING, PMIDFLOAT));

CREATE TABLE DATATYPES ( ID INT NOT NULL, BOOLEANDATA BOOLEAN, CHARDATA CHAR, SHORTDATA SMALLINT, INTDATA INT, INTDATA2 INT, LONGDATA BIGINT, DBLDATA DOUBLE, FLOATDATA FLOAT, ENUMODATA INT, ENUMSDATA VARCHAR(25), BYTEDATA SMALLINT, TRANS SMALLINT , BYTEARRAYDATA BLOB(6M), CHARARRAYDATA VARCHAR(448), CONSTRAINT PK_DATATYPES PRIMARY KEY (ID));

CREATE TABLE DATATYPES2 ( DATATYPES2_ID DATE NOT NULL, DATEDATA DATE, TIMEDATA TIME, TSDATA TIMESTAMP, CONSTRAINT PK_DATATYPES2 PRIMARY KEY (DATATYPES2_ID));

CREATE TABLE DATATYPES3 ( ID DECIMAL(18,0) NOT NULL, THEVALUE DECIMAL(18,0), CONSTRAINT PK_DATATYPES3 PRIMARY KEY (ID));

CREATE TABLE PURCHASE_ORDER (ID INT NOT NULL, TOTAL INT, DESCRIPTION VARCHAR(50), CONSTRAINT PK_PURCHASE_ORDER PRIMARY KEY (ID));

CREATE TABLE GENERATOR_TABLE (PK_COL VARCHAR(10), VAL_COL INT, CONSTRAINT GENERATOR_TABLE_PK PRIMARY KEY (PK_COL) );
INSERT into GENERATOR_TABLE(PK_COL, VAL_COL) values ('DT_ID', 1) ;
INSERT into GENERATOR_TABLE(PK_COL, VAL_COL) values ('DT1_ID', 1) ;
INSERT into GENERATOR_TABLE(PK_COL, VAL_COL) values ('DT2_ID', 100) ;
INSERT into GENERATOR_TABLE(PK_COL, VAL_COL) values ('DT3_ID', 1000) ;

CREATE TABLE SEQUENCE (SEQ_NAME VARCHAR(10), SEQ_COUNT INT, CONSTRAINT SEQUENCE_PK PRIMARY KEY (SEQ_NAME) );
INSERT into SEQUENCE(SEQ_NAME, SEQ_COUNT) values ('SEQ_GEN', 0) ;

CREATE TABLE ORDER1 (ID INT PRIMARY KEY NOT NULL, TOTALPRICE DOUBLE , FK1_FOR_ITEM INT);

CREATE TABLE ORDER2 (ID INT PRIMARY KEY NOT NULL, TOTALPRICE DOUBLE , FK2_FOR_ITEM INT);

CREATE TABLE ORDER3 (ID INT PRIMARY KEY NOT NULL, TOTALPRICE DOUBLE , FK3_FOR_ITEM INT);


CREATE TABLE ITEM (ID INT PRIMARY KEY, ITEMNAME VARCHAR(255)) ;

ALTER TABLE ORDER1 add constraint FK1_FOR_ITEM Foreign Key (FK1_FOR_ITEM) references ITEM(ID) ;
ALTER TABLE ORDER2 add constraint FK2_FOR_ITEM Foreign Key (FK2_FOR_ITEM) references ITEM(ID) ;
ALTER TABLE ORDER3 add constraint FK3_FOR_ITEM Foreign Key (FK3_FOR_ITEM) references ITEM(ID) ;

CREATE TABLE MEMBER (MEMBER_ID INT NOT NULL, MEMBER_NAME VARCHAR(255), DUES SMALLINT, VERSION INT, DONATION DECIMAL(18,0), CONSTRAINT PK_MEMBER PRIMARY KEY (MEMBER_ID)) ;

CREATE TABLE ACCOUNT (ID INT NOT NULL, BALANCE DOUBLE, DEPOSIT DOUBLE, WITHDRAW DOUBLE, CONSTRAINT PK_ACCOUNT PRIMARY KEY (ID)) ;

CREATE TABLE SEMESTER (ID INTEGER NOT NULL, PRIMARY KEY (ID)) ;

CREATE TABLE STUDENT_COURSE (Student_ID INTEGER NOT NULL, courses_ID INTEGER NOT NULL, PRIMARY KEY (Student_ID, courses_ID)) ;

CREATE TABLE STUDENT (ID INTEGER NOT NULL, STUDENTNAME VARCHAR(255), PRIMARY KEY (ID)) ;

CREATE TABLE COURSE (ID INTEGER NOT NULL, COURSENAME VARCHAR(255), PRIMARY KEY (ID)) ;

CREATE TABLE ENROLLMENTS (STUDENT INTEGER NOT NULL, ENROLLMENT_KEY INTEGER NOT NULL, SEMESTER INTEGER NOT NULL, PRIMARY KEY (STUDENT, ENROLLMENT_KEY, SEMESTER));

CREATE TABLE COURSE_STUDENT (COURSE_ID INTEGER NOT NULL, STUDENT_ID INTEGER NOT NULL, STUDENTS_ORDER INTEGER, PRIMARY KEY (COURSE_ID , STUDENT_ID)); 

ALTER TABLE STUDENT_COURSE ADD CONSTRAINT STDNTCOURSEStdntID FOREIGN KEY (Student_ID) REFERENCES STUDENT (ID) ;
ALTER TABLE STUDENT_COURSE ADD CONSTRAINT STDNTCOURSEcrsesID FOREIGN KEY (courses_ID) REFERENCES COURSE (ID) ;
ALTER TABLE ENROLLMENTS ADD CONSTRAINT ENROLLMENTSSTUDENT FOREIGN KEY (STUDENT) REFERENCES STUDENT (ID) ;
ALTER TABLE ENROLLMENTS ADD CONSTRAINT NROLLMENTSSEMESTER FOREIGN KEY (SEMESTER) REFERENCES SEMESTER (ID) ;
ALTER TABLE COURSE_STUDENT ADD CONSTRAINT CRSESTUDENTCurseID FOREIGN KEY (COURSE_ID) REFERENCES COURSE (ID) ;
ALTER TABLE COURSE_STUDENT ADD CONSTRAINT CRSSTUDENTstdntsID FOREIGN KEY (STUDENT_ID) REFERENCES STUDENT (ID) ;

CREATE TABLE NOENTITYLISTENER_TABLE(ID BIGINT  PRIMARY KEY NOT NULL);

CREATE TABLE COURSE_2(ID BIGINT NOT NULL,NAME VARCHAR(255));

CREATE TABLE STUDENT_2(ID BIGINT NOT NULL,NAME VARCHAR(255));

CREATE TABLE STUDENT_2_COURSE_2(COURSES_ID BIGINT,STUDENTS_ID BIGINT);

CREATE TABLE NAMEONLYINXML(ID BIGINT);

CREATE TABLE NAMEONLYINANNOTATION(ID BIGINT);

CREATE TABLE NAMEOVERRIDE (ID BIGINT);

CREATE TABLE  NOENTITYANNOTATION(ID BIGINT);

CREATE TABLE BOOKSTORE(ID BIGINT NOT NULL,NAME VARCHAR(255),LOCATION VARCHAR(255));

CREATE TABLE COMPLAINT(ID BIGINT NOT NULL, COMPLAINTNUMBER INT, NAME VARCHAR(255), ADDRESS VARCHAR(255));

CREATE TABLE MOVIETICKET(ID BIGINT NOT NULL, FILMNAME VARCHAR(255), FILMCODE VARCHAR(255));

CREATE TABLE BOOK(ID BIGINT NOT NULL, NAME VARCHAR(255), STATEOFUSA VARCHAR(255));

CREATE TABLE LAWBOOK(ID BIGINT NOT NULL, BOOK_NAME VARCHAR(255), CATEGORY VARCHAR(255),PUBLISHER VARCHAR(255),COST INT);

CREATE TABLE EMPLOYEE_2(ID BIGINT NOT NULL, CODE  VARCHAR(255), DEPARTMENT_ID BIGINT);

CREATE TABLE DEPARTMENT_2(ID BIGINT NOT NULL,NAME  VARCHAR(255));

CREATE TABLE THEATRELOCATION(ID BIGINT NOT NULL, CODE  VARCHAR(255));

CREATE TABLE THEATRECOMPANY(ID BIGINT NOT NULL,NAME  VARCHAR(255));

CREATE TABLE THEATRELOCATION_THEATRECOMPANY(COMPANIES_ID BIGINT, LOCATIONS_ID BIGINT);

CREATE TABLE STORE(ID BIGINT NOT NULL, NAME VARCHAR(255));

CREATE TABLE CUSTOMERS(ID BIGINT NOT NULL, CUSTNAME VARCHAR(255), STORE_ID BIGINT);

CREATE TABLE CONSUMER(ID BIGINT NOT NULL);

CREATE TABLE RETAILORDER(ID BIGINT NOT NULL, COST DOUBLE);

CREATE TABLE RETAILORDER_CONSUMER(CONSUMERS_ID  BIGINT NOT NULL,ORDERS_ID  BIGINT NOT NULL);

CREATE TABLE THEATRELOCATION1(ID BIGINT NOT NULL, CODE  VARCHAR(255),TCOMP_ID BIGINT);

CREATE TABLE THEATRECOMPANY1(ID BIGINT NOT NULL,NAME  VARCHAR(255));

CREATE TABLE CUBICLE(ID BIGINT NOT NULL , LOCATION VARCHAR(255), PRIMARY KEY(ID,LOCATION));

CREATE TABLE HARDWARE(ID BIGINT NOT NULL, CODE VARCHAR(255),CUBE_ID BIGINT NOT NULL, CUBE_LOCATION VARCHAR(255));

CREATE TABLE CUSTOMER1(ID BIGINT NOT NULL, NAME VARCHAR(255), CONSTRAINT PK_CUSTOMER1 PRIMARY KEY (ID));

CREATE  TABLE RETAILORDER1(ID BIGINT NOT NULL, COST DOUBLE);

CREATE TABLE  CUST_ORDER(CUSTID BIGINT NOT NULL,ORDERID BIGINT NOT NULL);


CREATE  TABLE RETAILORDER2(ID BIGINT NOT NULL, COST DOUBLE, FK_FOR_CUSTOMER1 BIGINT );

ALTER TABLE RETAILORDER2 ADD CONSTRAINT FK_FOR_CUST FOREIGN KEY(FK_FOR_CUSTOMER1) REFERENCES CUSTOMER1(ID);



CREATE TABLE UNI1X1PROJECT (PROJID BIGINT NOT NULL, BUDGET FLOAT, NAME VARCHAR(255), PRIMARY KEY (PROJID));
CREATE TABLE UNI1X1PERSON (ID BIGINT NOT NULL, NAME VARCHAR(255), PROJECT_PROJID BIGINT, PRIMARY KEY (ID));
ALTER TABLE UNI1X1PERSON ADD CONSTRAINT N1X1PRSNPRJCTPRJID FOREIGN KEY (PROJECT_PROJID) REFERENCES UNI1X1PROJECT (PROJID);



CREATE TABLE UNI1XMPERSON_UNI1XMPROJECT (Uni1XMPerson_ID BIGINT NOT NULL, projects_ID BIGINT NOT NULL, PRIMARY KEY (Uni1XMPerson_ID, projects_ID));
CREATE TABLE UNI1XMPROJECT (ID BIGINT NOT NULL, NAME VARCHAR(255), BUDGET FLOAT, PRIMARY KEY (ID));
CREATE TABLE UNI1XMPERSON (ID BIGINT NOT NULL, NAME VARCHAR(255), PRIMARY KEY (ID));
ALTER TABLE UNI1XMPERSON_UNI1XMPROJECT ADD CONSTRAINT N1XMPRSNNn1XMPrsnD FOREIGN KEY (Uni1XMPerson_ID) REFERENCES UNI1XMPERSON (ID);
ALTER TABLE UNI1XMPERSON_UNI1XMPROJECT ADD CONSTRAINT N1XMPRSNN1XprjctsD FOREIGN KEY (projects_ID) REFERENCES UNI1XMPROJECT (ID);



CREATE TABLE UNIMX1PROJECT (ID BIGINT NOT NULL, NAME VARCHAR(255), BUDGET FLOAT, PRIMARY KEY (ID));
CREATE TABLE UNIMX1PERSON (ID BIGINT NOT NULL, NAME VARCHAR(255), UNIMX1PROJECT_ID BIGINT, PRIMARY KEY (ID));
ALTER TABLE UNIMX1PERSON ADD CONSTRAINT NMX1PRSNNMX1PRJCTD FOREIGN KEY (UNIMX1PROJECT_ID) REFERENCES UNIMX1PROJECT (ID);



CREATE TABLE UNIMXMPERSON (ID BIGINT NOT NULL, NAME VARCHAR(255), PRIMARY KEY (ID));
CREATE TABLE UNIMXMPROJECT (ID BIGINT NOT NULL, NAME VARCHAR(255), BUDGET FLOAT, PRIMARY KEY (ID));
CREATE TABLE UNIMXMPERSON_UNIMXMPROJECT (UniMXMPerson_ID BIGINT NOT NULL, UniMXMProject_ID BIGINT NOT NULL, PRIMARY KEY (UniMXMPerson_ID, UniMXMProject_ID));
ALTER TABLE UNIMXMPERSON_UNIMXMPROJECT ADD CONSTRAINT NMXMPRSNNnMXMPrsnD FOREIGN KEY (UniMXMPerson_ID) REFERENCES UNIMXMPERSON (ID);
ALTER TABLE UNIMXMPERSON_UNIMXMPROJECT ADD CONSTRAINT NMXMPRSNnMXMPrjctD FOREIGN KEY (UniMXMProject_ID) REFERENCES UNIMXMPROJECT (ID);



CREATE TABLE BIDIR1X1PERSON (ID BIGINT NOT NULL, NAME VARCHAR(255), PROJECT_PROJID BIGINT, PRIMARY KEY (ID));
CREATE TABLE BIDIR1X1PROJECT (PROJID BIGINT NOT NULL, BUDGET FLOAT, NAME VARCHAR(255), PRIMARY KEY (PROJID));
ALTER TABLE BIDIR1X1PERSON ADD CONSTRAINT BDR1X1PRSPRJCTPRJD FOREIGN KEY (PROJECT_PROJID) REFERENCES BIDIR1X1PROJECT (PROJID);



CREATE TABLE BIDIR1XMPERSON (ID BIGINT NOT NULL, NAME VARCHAR(255), PRIMARY KEY (ID));
CREATE TABLE BIDIR1XMPROJECT (ID BIGINT NOT NULL, NAME VARCHAR(255), BUDGET FLOAT, BIDIR1XMPERSON_ID BIGINT, PRIMARY KEY (ID));
ALTER TABLE BIDIR1XMPROJECT ADD CONSTRAINT BDR1XMPBDR1XMPRSND FOREIGN KEY (BIDIR1XMPERSON_ID) REFERENCES BIDIR1XMPERSON (ID);



CREATE TABLE BIDIRMX1PROJECT (ID BIGINT NOT NULL, NAME VARCHAR(255), BUDGET FLOAT, PRIMARY KEY (ID));
CREATE TABLE BIDIRMX1PERSON (ID BIGINT NOT NULL, biDirMX1Persons_ORDER INT, NAME VARCHAR(255), UNIMX1PROJECT_ID BIGINT, PRIMARY KEY (ID));
ALTER TABLE BIDIRMX1PERSON ADD CONSTRAINT BDRMX1PRNMX1PRJCTD FOREIGN KEY (UNIMX1PROJECT_ID) REFERENCES BIDIRMX1PROJECT (ID);



CREATE TABLE BIDIRMXMPERSON_BIDIRMXMPROJECT (BIDIRMXMPerson_ID BIGINT NOT NULL, BIDIRMXMProject_ID BIGINT NOT NULL, PRIMARY KEY (BIDIRMXMPerson_ID, BIDIRMXMProject_ID));
CREATE TABLE BIDIRMXMPERSON (ID BIGINT NOT NULL, NAME VARCHAR(255), PRIMARY KEY (ID));
CREATE TABLE BIDIRMXMPROJECT (ID BIGINT NOT NULL, NAME VARCHAR(255), BUDGET FLOAT, PRIMARY KEY (ID));
ALTER TABLE BIDIRMXMPERSON_BIDIRMXMPROJECT ADD CONSTRAINT BDRMXMPBDRMXMPrsnD FOREIGN KEY (BIDIRMXMPerson_ID) REFERENCES BIDIRMXMPERSON (ID);
ALTER TABLE BIDIRMXMPERSON_BIDIRMXMPROJECT ADD CONSTRAINT BDRMXMBDRMXMPrjctD FOREIGN KEY (BIDIRMXMProject_ID) REFERENCES BIDIRMXMPROJECT (ID);



CREATE TABLE DID1DEPENDENT (NAME VARCHAR(255) NOT NULL, EMP_ID BIGINT NOT NULL, PRIMARY KEY (NAME, EMP_ID));
CREATE TABLE DID1EMPLOYEE (ID BIGINT NOT NULL, NAME VARCHAR(255), PRIMARY KEY (ID));
ALTER TABLE DID1DEPENDENT ADD CONSTRAINT DID1DEPENDENTEMPID FOREIGN KEY (EMP_ID) REFERENCES DID1EMPLOYEE (ID);



CREATE TABLE DID1BDEPENDENT (NAME VARCHAR(255) NOT NULL, EMP_ID BIGINT, PRIMARY KEY (NAME, EMP_ID));
CREATE TABLE DID1BEMPLOYEE (ID BIGINT NOT NULL, NAME VARCHAR(255), PRIMARY KEY (ID));
ALTER TABLE DID1BDEPENDENT ADD CONSTRAINT DID1BDEPENDENTMPID FOREIGN KEY (EMP_ID) REFERENCES DID1BEMPLOYEE (ID);



CREATE TABLE DID2EMPLOYEE (FIRSTNAME VARCHAR(255) NOT NULL, LASTNAME VARCHAR(255) NOT NULL, EMPNO INTEGER, PRIMARY KEY (FIRSTNAME, LASTNAME));
CREATE TABLE DID2DEPENDENT (NAME VARCHAR(255) NOT NULL, FIRSTNAME VARCHAR(255) NOT NULL, LASTNAME VARCHAR(255) NOT NULL, PRIMARY KEY (NAME, FIRSTNAME, LASTNAME));
ALTER TABLE DID2DEPENDENT ADD CONSTRAINT DD2DPENDENTFRSTNME FOREIGN KEY (FIRSTNAME, LASTNAME) REFERENCES DID2EMPLOYEE (FIRSTNAME, LASTNAME);



CREATE TABLE DID2BEMPLOYEE (LASTNAME VARCHAR(255) NOT NULL, FIRSTNAME VARCHAR(255) NOT NULL, EMPNO INTEGER, PRIMARY KEY (LASTNAME, FIRSTNAME));
CREATE TABLE DID2BDEPENDENT (NAME VARCHAR(255) NOT NULL, LASTNAME VARCHAR(255) NOT NULL, FIRSTNAME VARCHAR(255) NOT NULL, PRIMARY KEY (NAME, LASTNAME, FIRSTNAME));
ALTER TABLE DID2BDEPENDENT ADD CONSTRAINT DD2BDPENDENTLSTNME FOREIGN KEY (LASTNAME, FIRSTNAME) REFERENCES DID2BEMPLOYEE (LASTNAME, FIRSTNAME);



CREATE TABLE DID3EMPLOYEE (FIRSTNAME VARCHAR(255) NOT NULL, LASTNAME VARCHAR(255) NOT NULL, PRIMARY KEY (FIRSTNAME, LASTNAME));
CREATE TABLE DID3DEPENDENT (NAME VARCHAR(255) NOT NULL, FIRSTNAME VARCHAR(255) NOT NULL, LASTNAME VARCHAR(255) NOT NULL, PRIMARY KEY (NAME, FIRSTNAME, LASTNAME));
ALTER TABLE DID3DEPENDENT ADD CONSTRAINT DD3DPENDENTFRSTNME FOREIGN KEY (FIRSTNAME, LASTNAME) REFERENCES DID3EMPLOYEE (FIRSTNAME, LASTNAME);



CREATE TABLE DID3BEMPLOYEE (LASTNAME VARCHAR(255) NOT NULL, FIRSTNAME VARCHAR(255) NOT NULL, PRIMARY KEY (LASTNAME, FIRSTNAME));
CREATE TABLE DID3BDEPENDENT (NAME VARCHAR(255) NOT NULL, LASTNAME VARCHAR(255) NOT NULL, FIRSTNAME VARCHAR(255) NOT NULL, PRIMARY KEY (NAME, LASTNAME, FIRSTNAME));
ALTER TABLE DID3BDEPENDENT ADD CONSTRAINT DD3BDPENDENTLSTNME FOREIGN KEY (LASTNAME, FIRSTNAME) REFERENCES DID3BEMPLOYEE (LASTNAME, FIRSTNAME);



CREATE TABLE DID4MEDICALHISTORY (DOCTORNAME VARCHAR(255), PATIENT_SSN VARCHAR(255) NOT NULL, PRIMARY KEY (PATIENT_SSN));
CREATE TABLE DID4PERSON (SSN VARCHAR(255) NOT NULL, NAME VARCHAR(255), PRIMARY KEY (SSN));
ALTER TABLE DID4MEDICALHISTORY ADD CONSTRAINT DD4MDCLHSTRPTNTSSN FOREIGN KEY (PATIENT_SSN) REFERENCES DID4PERSON (SSN);



CREATE TABLE DID4BMEDICALHISTORY (ID VARCHAR(255) NOT NULL, DOCTORNAME VARCHAR(255), PRIMARY KEY (ID));
CREATE TABLE DID4BPERSON (SSN VARCHAR(255) NOT NULL, NAME VARCHAR(255), PRIMARY KEY (SSN));
ALTER TABLE DID4BMEDICALHISTORY ADD CONSTRAINT DD4BMDCLHSTPTNTSSN FOREIGN KEY (ID) REFERENCES DID4BPERSON (SSN);



CREATE TABLE DID5PERSON (FIRSTNAME VARCHAR(255) NOT NULL, LASTNAME VARCHAR(255) NOT NULL, SSN VARCHAR(255), PRIMARY KEY (FIRSTNAME, LASTNAME));
CREATE TABLE DID5MEDICALHISTORY (DOCTORNAME VARCHAR(255), FIRSTNAME VARCHAR(255) NOT NULL, LASTNAME VARCHAR(255) NOT NULL, PRIMARY KEY (FIRSTNAME, LASTNAME));
ALTER TABLE DID5MEDICALHISTORY ADD CONSTRAINT DD5MDCLHSTRYFRSTNM FOREIGN KEY (FIRSTNAME, LASTNAME) REFERENCES DID5PERSON (FIRSTNAME, LASTNAME);



CREATE TABLE DID5BMEDICALHISTORY (DOCTORNAME VARCHAR(255), LASTNAME VARCHAR(255) NOT NULL, FIRSTNAME VARCHAR(255) NOT NULL, PRIMARY KEY (LASTNAME, FIRSTNAME));
CREATE TABLE DID5BPERSON (LASTNAME VARCHAR(255) NOT NULL, FIRSTNAME VARCHAR(255) NOT NULL, SSN VARCHAR(255), PRIMARY KEY (LASTNAME, FIRSTNAME));
ALTER TABLE DID5BMEDICALHISTORY ADD CONSTRAINT DD5BMDCLHSTRYLSTNM FOREIGN KEY (LASTNAME, FIRSTNAME) REFERENCES DID5BPERSON (LASTNAME, FIRSTNAME);



CREATE TABLE DID6MEDICALHISTORY (DOCTORNAME VARCHAR(255), FIRSTNAME VARCHAR(255) NOT NULL, LASTNAME VARCHAR(255) NOT NULL, PRIMARY KEY (FIRSTNAME, LASTNAME));
CREATE TABLE DID6PERSON (SSN VARCHAR(255), FIRSTNAME VARCHAR(255) NOT NULL, LASTNAME VARCHAR(255) NOT NULL, PRIMARY KEY (FIRSTNAME, LASTNAME));
ALTER TABLE DID6MEDICALHISTORY ADD CONSTRAINT DD6MDCLHSTRYFRSTNM FOREIGN KEY (FIRSTNAME, LASTNAME) REFERENCES DID6PERSON (FIRSTNAME, LASTNAME);


CREATE TABLE DID6BPERSON (SSN VARCHAR(255), LASTNAME VARCHAR(255) NOT NULL, FIRSTNAME VARCHAR(255) NOT NULL, PRIMARY KEY (LASTNAME, FIRSTNAME));
CREATE TABLE DID6BMEDICALHISTORY (DOCTORNAME VARCHAR(255), LASTNAME VARCHAR(255) NOT NULL, FIRSTNAME VARCHAR(255) NOT NULL, PRIMARY KEY (LASTNAME, FIRSTNAME));
ALTER TABLE DID6BMEDICALHISTORY ADD CONSTRAINT DD6BMDCLHSTRYLSTNM FOREIGN KEY (LASTNAME, FIRSTNAME) REFERENCES DID6BPERSON (LASTNAME, FIRSTNAME);


CREATE TABLE EMP_MAPKEYCOL(ID INT NOT NULL, FIRSTNAME VARCHAR(255) , LASTNAME VARCHAR(255), HIREDATE DATE, SALARY REAL NOT NULL, STATUS VARCHAR(255),  FK_MGR INT, FK_DEPT INT, FK_DEPT3 INT, FK_DEPT4 INT, FK_PROJECT INT , FK_INS INT, OFFICE_ID VARCHAR(255), LASTNAMEEMPLOYEES_KEY VARCHAR(255), CONSTRAINT PK_EMP PRIMARY KEY (ID)) ;
ALTER TABLE EMP_MAPKEYCOL ADD CONSTRAINT FK_DEPT1 FOREIGN KEY (FK_DEPT) REFERENCES DEPARTMENT (ID) ;
ALTER TABLE EMP_MAPKEYCOL ADD CONSTRAINT FK_DEPT3 FOREIGN KEY (FK_DEPT3) REFERENCES DEPARTMENT (ID) ;
ALTER TABLE EMP_MAPKEYCOL ADD CONSTRAINT FK_DEPT4 FOREIGN KEY (FK_DEPT4) REFERENCES DEPARTMENT (ID) ;

CREATE TABLE EMP_MAPKEYCOL2(ID INT NOT NULL, LASTNAME VARCHAR(255), THEDATE DATE ,FK_DEPT5 INT,  CONSTRAINT PK_EMP2 PRIMARY KEY (ID)) ;
ALTER TABLE EMP_MAPKEYCOL2 ADD CONSTRAINT FK_DEPT5 FOREIGN KEY (FK_DEPT5) REFERENCES DEPARTMENT2 (ID) ;

CREATE TABLE EMPLOYEE_EMBEDED_ADDRESS (ID INTEGER NOT NULL, FIRSTNAME VARCHAR(255), LASTNAME VARCHAR(255), PRIMARY KEY (ID));
CREATE TABLE COLTAB_EMP_EMBEDED_ADDRESS (ADDRESS_LOCATION VARCHAR(255), STREET VARCHAR(255), STATE VARCHAR(255), ZIP VARCHAR(255), CITY VARCHAR(255), ID VARCHAR(255), EMPEMBADDRID INTEGER);
ALTER TABLE COLTAB_EMP_EMBEDED_ADDRESS ADD CONSTRAINT FK_EMPEMBADDRID FOREIGN KEY (EMPEMBADDRID) REFERENCES EMPLOYEE_EMBEDED_ADDRESS (ID) ;


CREATE SEQUENCE SEQGENERATOR AS INT START WITH 10;


CREATE TABLE HIBERNATE_SEQUENCE(NEXT_VAL INT) ;
INSERT into HIBERNATE_SEQUENCE(NEXT_VAL) values (0) ;
 
CREATE SEQUENCE HIBERNATE_SEQUENCE AS INT START WITH 1 ;
CREATE SEQUENCE DATATYPES_SEQ START WITH 1 INCREMENT by 50;

CREATE TABLE CRITERIA_TEST_TABLE (ID INTEGER PRIMARY KEY NOT NULL, DATE_VAL DATE, INT_VAL INTEGER, STR_VAL_1 VARCHAR(255), STR_VAL_2 VARCHAR(255), TIME_VAL TIME);
CREATE TABLE CRITERIA_TEST_COLTABLE(ENT_ID INTEGER NOT NULL, COLVAL VARCHAR(255), CONSTRAINT FK_CRITERIA_TEST_COLTABLE_ENT_ID FOREIGN KEY (ENT_ID) REFERENCES CRITERIA_TEST_TABLE (ID));

CREATE TABLE UUIDTYPE (ID VARCHAR(96) NOT NULL, NAME VARCHAR(255), PRIMARY KEY (ID));
